### ISSUE TITLE
Plugin typescript: @rollup/plugin-typescript TS5023: Unknown compiler option 'reflection'.

### ISSUE THREAD

**Issue by khusamov** [Hookyns/tst-reflect#36]
I tried to configure Rollup and found an error!

"rollup": "^2.70.1",

tsconfig.json

```json
{
	"compilerOptions": {
		"moduleResolution": "Node",
		"module": "ES2020",
		"target": "ES2020",
		"strict": true,
		"sourceMap": true,
		"plugins": [
			{
				"transform": "tst-reflect-transformer"
			}
		],
		"reflection": {
			"metadata": false,
			"debugMode": false
		}
	}
}

```

Error:

```
(!) Plugin typescript: @rollup/plugin-typescript TS5023: Unknown compiler option 'reflection'.
[!] (plugin typescript) Error: @rollup/plugin-typescript: Couldn't process compiler options
Error: @rollup/plugin-typescript: Couldn't process compiler options
    at error (/Users/khusamov/Documents/repo/github.com/khusamov/typescript-reflection/tst-reflect-rollup/node_modules/rollup/dist/shared/rollup.js:198:30)
    at throwPluginError (/Users/khusamov/Documents/repo/github.com/khusamov/typescript-reflection/tst-reflect-rollup/node_modules/rollup/dist/shared/rollup.js:21847:12)
    at Object.error (/Users/khusamov/Documents/repo/github.com/khusamov/typescript-reflection/tst-reflect-rollup/node_modules/rollup/dist/shared/rollup.js:22570:20)
    at emitParsedOptionsErrors (/Users/khusamov/Documents/repo/github.com/khusamov/typescript-reflection/tst-reflect-rollup/node_modules/@rollup/plugin-typescript/dist/index.js:356:17)
    at Object.buildStart (/Users/khusamov/Documents/repo/github.com/khusamov/typescript-reflection/tst-reflect-rollup/node_modules/@rollup/plugin-typescript/dist/index.js:736:13)
    at /Users/khusamov/Documents/repo/github.com/khusamov/typescript-reflection/tst-reflect-rollup/node_modules/rollup/dist/shared/rollup.js:22779:37
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 2)
    at /Users/khusamov/Documents/repo/github.com/khusamov/typescript-reflection/tst-reflect-rollup/node_modules/rollup/dist/shared/rollup.js:23567:13
    at catchUnfinishedHookActions (/Users/khusamov/Documents/repo/github.com/khusamov/typescript-reflection/tst-reflect-rollup/node_modules/rollup/dist/shared/rollup.js:23077:20)

```

**Comment by Hookyns** [comment]
Well it seems that Rollup validates tsconfig and yeah `reflection` is not an official property.
You can remove that property so default configuration will be used.

I'll look into it and I'll try to find out how to declare that config property or I'll have to create separad config or idk..
